# Generated by Django 5.1.6 on 2025-04-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(default='Đang cập nhật'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
